services:
    Oka\PaginationBundle\Pagination\FilterExpression\:
        resource: '../../Pagination/FilterExpression/*'
        exclude: '../../Pagination/FilterExpression/{EvaluationResult.php,FilterExpressionHandler.php}'
        tags:
          - {name: oka_pagination.filter_expression}

    oka_pagination.pagination_configuration_bag_configurator:
        class: Oka\PaginationBundle\Pagination\ConfigurationBagConfigurator
        arguments: ['%oka_pagination.pagination_managers%']

    oka_pagination.pagination_configuration_bag:
        class: Oka\PaginationBundle\Pagination\ConfigurationBag
        configurator: '@oka_pagination.pagination_configuration_bag_configurator'

    oka_pagination.page_route_loader:
        class: Oka\PaginationBundle\Routing\PageRouteLoader
        arguments: ['@oka_pagination.pagination_configuration_bag']
        tags:
          - {name: routing.route_loader}

    oka_pagination.filter_expression_handler:
        class: Oka\PaginationBundle\Pagination\FilterExpression\FilterExpressionHandler
        arguments: [[]]

    oka_pagination.pagination_manager:
        public: true
        class: Oka\PaginationBundle\Pagination\PaginationManager
        arguments: ['', '@oka_pagination.pagination_configuration_bag', '@oka_pagination.filter_expression_handler']

    Oka\PaginationBundle\Pagination\FilterExpression\FilterExpressionHandler: '@oka_pagination.filter_expression_handler'
    Oka\PaginationBundle\Pagination\PaginationManager: '@oka_pagination.pagination_manager'
